Fix minor typo in gocdb_schema.xml
GOCDB/gocdb pull request #316
Opened 2021-11-16 10:42 UTC by GRyall

2021-11-16 11:37 UTC, ineilson requested changes

2021-11-16 11:37 UTC, ineilson commented on config/gocdb_schema.xml
> +        <!--Allows most chracters, leading and trailing white space, but requires at least one non-whitespace chracter -->
```suggestion
        <!--Allows most characters, leading and trailing white space, but requires at least one non-whitespace character -->
```

2022-02-14 17:11 UTC, tofu-rocketry approved these changes

2022-05-24 15:56 UTC, gregcorbett approved these changes
LGTM :)

2022-05-24 15:57 UTC, merged