Release 5.9.0 to dev
GOCDB/gocdb pull request #346
Opened 2022-05-17 07:39 UTC by gregcorbett

It's running here: https://host-172-16-101-131.nubes.stfc.ac.uk/portal

2022-05-18 09:02 UTC, gregcorbett commented
I've [addressed](https://github.com/GOCDB/gocdb/compare/a5e75024e59b26428138b6425e71103552fd0a43..46b277184b07bbf703d8ca771f4dda7887ff443d) the low hanging fruit codeclimate raised.

2022-05-23 11:56 UTC, tofu-rocketry commented
What's 46b277184b07bbf703d8ca771f4dda7887ff443d doing in the release branch?

2022-05-23 13:49 UTC, tofu-rocketry commented
> it's a bug fix that means un-authenticated users can't get to the portal.

Ok, but why's a bug fix on a release branch?

2022-05-23 14:49 UTC, tofu-rocketry requested changes

2022-05-23 14:51 UTC, tofu-rocketry approved these changes

2022-05-23 15:48 UTC, merged