Make references to operational tools configurable (DRAFT TEST)
GOCDB/gocdb pull request #412
Opened 2022-12-19 14:30 UTC by rowan04

- added config options for helpdesk link, helpdesk support unit, request tracker and community documentation
- so that different instances of gocdb can have links point directly to their tooling, instead of having general references

2023-02-22 11:33 UTC, rowan04 commented
Note - this currently doesn't work and the gocdb webpage doesn't have the correct links. I am still working on this

2023-02-22 11:35 UTC, rowan04 commented on htdocs/web_portal/index.php
> +	    //require_once __DIR__.'/components/Draw_Components/draw_page_components.php';
This line is to be removed

2023-02-22 12:07 UTC, rowan04 commented on htdocs/web_portal/index.php
> +    $PHP = Get_File_Contents($phpDir."/".$PHP_Page_Name);
Here's the problem (line 724) - Get_File_Contents just gets the contents of the file, it doesn't execute it. Therefore the php parts aren't being executed, just written out. idk what to replace it with though

2023-02-22 12:22 UTC, rowan04 commented on htdocs/web_portal/index.php
> +    $PHP = Get_File_Contents($phpDir."/".$PHP_Page_Name);
Fixed this - I just used the commented out statements below I'd tried before! I had to use the `systemctl reload httpd` to update it, which is maybe why it hadn't worked before.

2023-02-22 14:21 UTC, gregcorbett commented
Hmmmmm, I wonder if moving the Help_And_Contact to be fully within the view/controller setup would be a cleaner solution than using `ob_start()` et al.

my_sites.php is a relatively small example of the view/controller setup in use:
- https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/controllers/my_sites.php
- https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/views/my_sites.php

So for this, you'd have to create, for example:
- `htdocs/web_portal/controllers/help_and_contact.php`. 
- `htdocs/web_portal/views/help_and_contact.php`. 

The controller is where the code in htdocs/web_portal/static_php/operationalLinks.php would go, except with the output contained in a `params` array.

The view is where the contents of `htdocs/web_portal/static_php/Help_And_Contact.php` would go, except with references to the `params` array, i.e. `params['HelpdeskLink']` instead of `$helpdeskLink`.

You'd have to add an additonal case for PageType=Help_And_Contact in [web_portal/index.php](https://github.com/GOCDB/gocdb/blob/dev/htdocs/), similar to the [My_Sites case](https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/index.php#L300), but it would mean less new code in index.php.

Could you give that a go?

2023-02-22 14:41 UTC, rowan04 commented
> Hmmmmm, I wonder if moving the Help_And_Contact to be fully within the view/controller setup would be a cleaner solution than using `ob_start()` et al.
> 
> my_sites.php is a relatively small example of the view/controller setup in use:
> 
> * https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/controllers/my_sites.php
> * https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/views/my_sites.php
> 
> So for this, you'd have to create, for example:
> 
> * `htdocs/web_portal/controllers/help_and_contact.php`.
> * `htdocs/web_portal/views/help_and_contact.php`.
> 
> The controller is where the code in htdocs/web_portal/static_php/operationalLinks.php would go, except with the output contained in a `params` array.
> 
> The view is where the contents of `htdocs/web_portal/static_php/Help_And_Contact.php` would go, except with references to the `params` array, i.e. `params['HelpdeskLink']` instead of `$helpdeskLink`.
> 
> You'd have to add an additonal case for PageType=Help_And_Contact in [web_portal/index.php](https://github.com/GOCDB/gocdb/blob/dev/htdocs/), similar to the [My_Sites case](https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/index.php#L300), but it would mean less new code in index.php.
> 
> Could you give that a go?

ok

2023-02-23 10:09 UTC, gregcorbett requested changes
see my previous comment

2023-03-14 16:40 UTC, gregcorbett approved these changes
This looks great :). I want to prepare the necassary config change, in a sandbox, at the same time I merge this.

2026-07-15 12:07 UTC, gregcorbett commented
rebasing to fix conflict

2026-07-15 12:40 UTC, merged